import product_builder

producto_capilar_nombre = ['Dermilid cabello y uñas 60 cápsulas', 'Multipilol Cabello uñas 60 capsulas', 'Multipilol Cabello y uñas 20 barritas', 'Dermilid champú frecuencia', 'Dermilid champú seco']
producto_capilar_precio = ['28.99', '28.99', '32.99', '12.99', '15.99']
producto_capilar_descripcion = ['Complemento alimenticio para el fortalecimiento y crecimiento del cabello y las uñas.', 'Complemento alimenticio para fortalecer y regenerar el cabello y las uñas.', 'Complemento alimenticio presentado en barrita de chocolate.', 'Champú dermatológico de máxima tolerancia de uso diario. Cuida el cabello y favorece su recuperación', 'Champú en polvo que limpia y desengrasa el cabello sin mojarlo.']
producto_capilar_indicacciones = ['Alopecia areata, Alopecia androgenética, Alopecia en telógeno, Alopecia en anágeno, Tricodistrofias, Seborrea capilar, Dermatitis seborreica, Distrofias ungueales', 'Alopecia areata, Alopecia androgenética, Alopecia en telógeno, Alopecia en anágeno, Tricodistrofias, Seborrea capilar, Dermatitis , seborreica, Distrofias ungueales.', 'Alopecia areata, Alopecia androgenética, Alopecia en telógeno, Alopecia en anágeno, Tricodistrofias, Seborrea capilar, Dermatitis seborreica, Distrofias ungueales', 'Higiene del cabello y cuero cabelludo., Favorecela recuperaccion fisiologica del cabello, dejandolo suave, suelto y facil de peinar. Proporciona volumen, brillo y elasticidad al recuperar su estructura. Alto poder de limpieza. Optima tolerancia', 'Para mantener el cabello desengrasado, con más volumen, más suelto y con más brillo. Indispensable en los estados seborreicos cutáneospilosos y en cabellos frágiles y/o quebradizos. En las alopecias seborreicas/androgenéticas. Uso diario.']
producto_capilar_composicion = ['Aceite de colza refinado, L-Cistina, Levadura de cerveza, Calcio hidrogeno, Fosfato anhidro, Hierro sulfato, Vitamina B3 (nicotinamida), Vitamina B5 (D-Calcium Pantothenato), Zinc Óxido, Vitamina B6 (Piridoxina Hidrocloruro), Vitamina B2 (Riboflavina), Vitamina B1 (Tiamina Mononitrato), Vitamina B12 (cianocobalamina), Vitamina B8 (Biotina), Cobre, sulfato anhidro, Lecitina de soja, Cera amarilla de abejas, Envolvente: Gelatina, Glicerina, Óxido de Hierro negro, Óxido de Hierro rojo.', 'Vitamina E, Vitamina B5 (D-Calcium Pantothenato), L-Cistina, Sulfato de zinc, Vitamina B6 (Piridoxina Hidrocloruro), Vitamina B2 (Riboflavina), Biotina, Magnesio, Sulfato de hierro, Vitamina B1 (Tiamina), Colorante.', 'Chocolate negro (60%) (pasta de cacao, azúcar, manteca de cacao, emulgente: lecitina de soja y vainilla), harina de trigo, aceite vegetal, L-Cistina, maltitol, leche desnatada en polvo, huevo fresco, levadura de cerveza, minerales (hierro y zinc), complejo vitamínico (E, B6, B1, B2, ácido pantoténico y biotina), levadura en polvo y sal.', 'Agua, Lauril Éter Sulfato de Sodio, Cloruro de Sodio, Cocamida DEA, Betaina de coco, Fenoxietanol, PEG-7 Glyceryl Cocoate, Parfume (Fragrancia), Cloruro de guar hidroxipropiltrimonio, Acido Citrico, Benzoato de sodio, Polyquaternium-7, Metilparabeno, Methylpropanediol, C.I. 19140 (FD&C Yellow N)', 'Talc, Sodium bicarbonate, Silica, Zinc oxide, Tannic acid, Nylon-12, Salicylic acid, Parfum.']
producto_capilar_modo_empleo = ['Se recomienda la toma de dos cápsulas al día durante un mínimo de tres meses. Las tomas podrán continuarse o repetirse tras un período de descanso según se estime necesario. Conviene ingerir las cápsulas con abundante líquido (agua, zumo de frutas,…). No superar las dosis recomendadas. Los complementos no deben utilizarse como sustitutos de una dieta variada y equilibrada. Mantener fuera del alcance de los niños más pequeños. APTO PARA CELÍACOS.', 'Ingerir una cápsula cada 12 horas o dos cápsulas de una sola vez cada 24 horas durante un plazo de 3 meses. No superar la dosis recomendadas. Los complementos no deben utilizarse como substituto de una dieta variada y equilibrada. Mantener fuera del alcance de los niños más pequeños.', 'Ingerir una barrita a cualquier hora del día durante un plazo de 8 a 10 semanas. Las tomas podrán continuarse o repetir, tras un período de descanso, según se estime necesario.No debe usarse como sustituto de una dieta equilibrada y variada. No superar la dosis diaria recomendada de una barrita. Un consumo excesivo puede tener efecto laxante. Mantener fuera del alcance de los niños más pequeños.Manténgase en lugar fresco y seco. No es apto para celíacos.', 'Aplicar una pequeña cantidad sobre el cabello previamente mojado y friccionar con suavidad hasta provocar suficiente espuma, manteniéndola de 2 a 4 minutos. Aclarar correctamente con abundante cantidad de agua hasta la total eliminación de la espuma. Si procede puede repetirse la operación. Por su excelente tolerancia puede utilizarse con la frecuencia que se precise o desee, incluso a diario.', 'Agitar antes de usarlo. Espolvorear aplicando una moderada cantidad por todo el cabello, preferentemente por las zonas centrales. Amasar, friccionando suavemente. Mantener de 2 a 4 minutos. Cepillar (peinar según costumbre)']


def dermilid_capilar_productos():
    productos = []

    for i in range(len(producto_capilar_nombre)):
        producto = product_builder.product(producto_capilar_nombre[i], producto_capilar_precio[i], producto_capilar_descripcion[i], producto_capilar_indicacciones[i], producto_capilar_composicion[i], producto_capilar_modo_empleo[i])
        productos.append(producto)